language: python
python:
  - "2.7"
    #- "3.3"    # travis doesn't have apt packages for Python 3
    #- "3.4"

branches:
  only:
    - master
    - travis

virtualenv:
  system_site_packages: true

install:
    #- pip install -r requirements.txt
  - sudo apt-get update
  - sudo apt-get install python-numpy python-scipy python-pyproj
  - pip install karta
  - pip install pyshp
  - pip install requests
  - pip install .

script:
  python tests/runtests.py

