language: python
python:
  - "2.7"
    #- "3.3"    # travis doesn't have apt packages for Python 3
    #- "3.4"

branches:
  only:
    - master
    - travis

before_install:
  - sudo apt-get install python-numpy
  - python -c "import pyproj"

install:
  - pip install karta
  - pip install requests
  - pip install pyproj
    #- pip install -r requirements.txt
  - pip install . -v

script:
  python tests/runtests.py

