language: python
python:
  - "2.7"
    #- "3.3"    # travis doesn't have apt packages for Python 3
    #- "3.4"

branches:
  only:
    - master
    - travis

before_install:
  - sudo apt-get install python-numpy python-scipy python-matplotlib python-pyproj

install:
  - pip install karta
  - pip install requests
    #- pip install -r requirements.txt
  - python install_gsw.py   # needed to put the extension module in place for tests
  - echo `find . -name *cgsw*
  - pip install . -v

script:
  python tests.py

